package org.dreambot.api.methods.skills;
public enum Skill {
  ATTACK, STRENGTH, DEFENCE, HITPOINTS, RANGED, PRAYER, MAGIC,
  COOKING, WOODCUTTING, FLETCHING, FISHING, FIREMAKING, CRAFTING,
  SMITHING, MINING, HERBLORE, AGILITY, THIEVING, SLAYER, FARMING,
  RUNECRAFTING, HUNTER, CONSTRUCTION;
}
